version: "3"

services:
  forgerock-challenge-app:
    build:
      context: .
    image: forgerock-challenge
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python server.py
